
import type { Directive } from '../types';

interface BuildRobotsTxtParams {
  userAgent: string;
  directives: Directive[];
  sitemap?: string;
  crawlDelay?: number;
}

export const buildRobotsTxt = ({
  userAgent,
  directives,
  sitemap,
  crawlDelay,
}: BuildRobotsTxtParams): string => {
  let content = `# Generated by Robots.txt Generator Pro - https://doodax.com\n`;
  content += `# ${new Date().toUTCString()}\n\n`;

  content += `User-agent: ${userAgent.trim() || '*'}\n`;

  directives.forEach(directive => {
    if (directive.path.trim()) {
      content += `${directive.type}: ${directive.path.trim()}\n`;
    }
  });

  if (crawlDelay && crawlDelay > 0) {
    content += `Crawl-delay: ${crawlDelay}\n`;
  }

  content += `\n# Sitemaps\n`;
  if (sitemap && sitemap.trim()) {
    content += `Sitemap: ${sitemap.trim()}\n`;
  }

  return content;
};
